# Generated by Django 4.0.4 on 2022-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars_nomi', models.CharField(max_length=10)),
                ('malumoti', models.TextField()),
                ('bolalarning_yoshi', models.IntegerField(default=1)),
                ('joy_soni', models.IntegerField(default=5)),
                ('dars_vaqti', models.DateTimeField()),
                ('dars_narxi', models.IntegerField(default=0)),
            ],
        ),
    ]
