# Generated by Django 4.0.4 on 2022-06-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogcha_ilova', '0002_lesson_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jamoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='jamoa _rasmlari')),
                ('ismi', models.CharField(max_length=100)),
                ('fani', models.CharField(max_length=100)),
                ('telegram', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
